[default]
MONGODB_URI="@jinja mongodb://{{this.MONGO_ROOT_USER}}:{{this.MONGO_ROOT_PASS}}@{{this.MONGO_HOST}}:{{this.MONGO_PORT}}/{{this.MONGO_DB}}?authSource=admin"

# Change development or production on .env
[development]
aws_access_key_id = ''
aws_secret_access_key = ''
telegram_token = ""
telegram_chat_id = 0
SMTP_HOST = ""
SMTP_PORT = "587"
SMTP_USER = ""
SMTP_PASSWORD = ""
SMTP_MSG_FROM = ''

MONGO_ROOT_USER="admin"
MONGO_ROOT_PASS="changeme"
MONGO_HOST="localhost"
MONGO_PORT=27017
MONGO_DB="dev-db"
# RESULT MONGODB_URI = "mongodb://admin:changeme@localhost:27017/dev-db?authSource=admin"

# Change development or production on .env
[production]
aws_access_key_id = ''
aws_secret_access_key = ''
telegram_token = ""
telegram_chat_id = 0
SMTP_HOST = ""
SMTP_PORT = "587"
SMTP_USER = ""
SMTP_PASSWORD = ""
SMTP_MSG_FROM = ''

MONGO_ROOT_USER="admin_prod"
MONGO_ROOT_PASS="changeme"
MONGO_HOST="localhost"
MONGO_PORT=27017
MONGO_DB="dev-db"
# RESULT MONGODB_URI = "mongodb://admin_prod:changeme@localhost:27017/prod-db?authSource=admin"

