[development]
aws_access_key_id = ''
aws_secret_access_key = ''
telegram_token = ""
telegram_chat_id = 0
SMTP_HOST = ""
SMTP_PORT = "587"
SMTP_USER = ""
SMTP_PASSWORD = ""
SMTP_MSG_FROM = ''

[production]
aws_access_key_id = ''
aws_secret_access_key = ''
telegram_token = ""
telegram_chat_id = 0
SMTP_HOST = ""
SMTP_PORT = "587"
SMTP_USER = ""
SMTP_PASSWORD = ""
SMTP_MSG_FROM = ''