version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo-dev
    env_file: .env    
    environment:
      - PUID= 1000
      - PGID= 1000
      - MONGO_INITDB_ROOT_USERNAME=${DYANCONF_MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DYANCONF_MONGO_ROOT_PASS}
      - MONGO_INITDB_DATABASE="mydb"
    ports:
      - 27017:27017
    volumes:
      - $HOME/.docker/database/dump_mongodb:/dump_mongodb
      - $HOME/.docker/database/mongodb:/data/db      
    restart: unless-stopped
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DYANCONF_MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DYANCONF_MONGO_ROOT_PASS}      
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=${DYANCONF_MONGO_PORT}
      - ME_CONFIG_BASICAUTH_USERNAME=${DYANCONF_MOGOEXPRESS_BASICAUTH_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DYANCONF_MONGOEXPRESS_BASICAUTH_PASS}      
    depends_on:
      - mongodb      
    networks:
      - mongo-compose-network
    restart: always


networks: 
    mongo-compose-network:
      driver: bridge
   